export { default as Home } from './Home';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Login } from './Login';
export { default as Quiz } from './Quiz';
export {default as Mophong} from './Mophong';
export { default as Register } from './Register';
export {default as QuizPage} from './QuizPage';
export {default as User} from './User';
export {default as PaySuccess} from './PaySuccess';
export {default as PaymentFail} from './PaymentFail';
export {default as Mentor} from './Mentor';
export {default as Payment} from './Payment';
export {default as Test} from './Test';
export {default as Staff} from './Staff';
export {default as Admin} from './Admin';