export {default as Navbar} from './navbar/Navbar';
export {default as About} from './About/About';
export {default as Course} from './Course/Course';
export {default as Facts} from './Facts/Facts';
export {default as Carousel} from './Carousel/Carousel';
export {default as Spinner} from './Spinner/Spinner';
export {default as Timetable} from './Timetable/Timetable';
export {default as TakeAttend} from './TakeAttend/TakeAttend';
export {default as CreateSlot} from './CreateSlot/CreateSlot';
export {default as Schedule} from './Schedule/Schedule';
export {default as License} from './Staff/License';
export {default as MentorList} from './Staff/MentorList';
export {default as StaffCourse} from './Staff/StaffCourse';
export {default as StaffQuiz} from './Staff/StaffQuiz';
export {default as NavbarStaff} from './navbar-staff/NavbarStaff';
export {default as StaffList} from './Admin/StaffList'
export {default as CourseList} from './Admin/CourseList'
export {default as GuestNavBar} from './navbar/GuestNavbar'
export {default as SlotTime} from './Staff/SlotTime'